name: Prisma Cloud IaC Scan

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  #schedule:
  #- cron: '26 17 * * 0'

jobs:
  prisma_cloud_iac_scan:
    runs-on: ubuntu-latest
    name: Run Prisma Cloud IaC Scan to check Compliance
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run Scan on IaC .tf files in the repository
        uses: prisma-cloud-shiftleft/iac-scan-action@53278c231c438216d99b463308a3cbed351ba0c3
        id: iac-scan
        with:
          prisma_api_url: "https://api2.prismacloud.io"
          access_key: ${{ secrets.PRISMA_CLOUD_ACCESS_KEY }}
          secret_key: ${{ secrets.PRISMA_CLOUD_SECRET_KEY }}
          asset_name: "my-repo-name"
          template_type: "TF"
          template_version: 0.13
          #scan_path: './terraform'
          #failure_criteria: 'High:2,Medium:3,Low:5,Operator:or'
      #- name: Upload scan result artifact
      #uses: actions/upload-artifact@v2
      #if: success() || failure()
      #with:
      #name: iac_scan_result
      #path: ${{ steps.iac-scan.outputs.iac_scan_result_path }}
